# Generated by Django 6.0.2 on 2026-03-31 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='account',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='tenure_months',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='related_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_kyc_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
