# Generated by Django 6.0.2 on 2026-03-31 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_loan_account_remove_loan_interest_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
    ]
